<?php

abstract class EventTypes
{

	const ORION_INITIALIZED = 'ORION_INITIALIZED';
	const ORION_BEFORE_DISPATCH = 'ORION_BEFORE_DISPATCH';
	const ORION_AFTER_DISPATCH = 'ORION_AFTER_DISPATCH';
	const ORION_BEFORE_LAYOUT = 'ORION_BEFORE_LAYOUT';
	const ORION_AFTER_LAYOUT = 'ORION_AFTER_LAYOUT';
	const ORION_BEFORE_VIEW = 'ORION_BEFORE_VIEW';
	const ORION_AFTER_VIEW = 'ORION_AFTER_VIEW';
	const ORION_BEFORE_QUERY = 'ORION_BEFORE_QUERY';
	const ORION_AFTER_QUERY = 'ORION_AFTER_QUERY';
	const ORION_BEFORE_ACTION = 'ORION_BEFORE_ACTION';
	const ORION_AFTER_ACTION = 'ORION_AFTER_ACTION';
	const ORION_BEFORE_DISPLAY = 'ORION_BEFORE_DISPLAY';
	const ORION_AFTER_DISPLAY = 'ORION_AFTER_DISPLAY';

}